name: Hello World Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  hello-world-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Echo the content of hello_world.txt
        run: cat hello_world.txt
